#!/bin/sh

# ------------------------------------------------------------------------------
# Copyright (C) 2014 Schneider Electric
#
# This file is part of "Mind Compiler" is free software: you can redistribute 
# it and/or modify it under the terms of the GNU Lesser General Public License 
# as published by the Free Software Foundation, either version 3 of the 
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT 
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more
# details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: mind@ow2.org
#
# Authors: Schneider Electric Mind4SE
# Contributors: 
# ------------------------------------------------------------------------------
# Optional ENV vars
# -----------------
#   MINDOC_OPTS - parameters passed to the Java VM running the mind compiler

## Launcher class name
LAUNCHER=org.ow2.mind.doc.Launcher

#echo $(dirname $0)/jar_launcher ${LAUNCHER} ${MINDOC_OPTS} ${LAUNCHER} "$@"
exec $(dirname $0)/jar_launcher ${LAUNCHER} ${MINDOC_OPTS} ${LAUNCHER} "$@"
